import { inspector } from '../data/demo-data.js';
import { $ } from '../utils/dom.js';
export const navItems=[['dashboard','Dashboard'],['scan','Scan Product'],['history','Inspections'],['report','Reports'],['analytics','Analytics'],['rules','Rules'],['products','Products']];
export function renderShell(){
 document.body.innerHTML=`<div id="toast-root"></div><section id="login"></section><div id="app" class="hidden min-h-screen"><aside class="sidebar"><div class="brand"><div class="brand-mark">✓</div><div><div class="brand-name">PackSure <span>AI</span></div><div class="brand-sub">INSPECTOR CONSOLE</div></div></div><div class="nav-caption">WORKSPACE</div><nav id="nav"></nav><div class="sidebar-bottom"><div class="region-chip"><span class="pulse-dot"></span><div><b>Live workspace</b><small>${inspector.region} · ${inspector.location}</small></div></div><div class="user-card"><div class="avatar">AS</div><div><b>${inspector.name}</b><small>${inspector.id}</small></div></div></div></aside><div class="main-shell"><header class="topbar"><div class="top-left"><button id="mobile-menu" class="mobile-menu">☰</button><div><div id="crumb" class="crumb">Dashboard</div><div class="crumb-sub">Legal Metrology Intelligence</div></div></div><div class="top-actions"><div class="live-status"><span class="pulse-dot"></span> Demo environment</div><button id="notifications" class="icon-btn">⌁<i></i></button><div class="top-profile"><div class="avatar">AS</div><span>${inspector.name}</span></div></div></header><div id="mobileNav" class="mobile-nav hidden"></div><main id="page-root"></main><footer class="app-footer">PackSure AI · Prototype for compliance assistance · Verify final regulatory determinations against current official requirements.</footer></div></div>`;
 const nav=$('#nav'), mobile=$('#mobileNav');
 nav.innerHTML=navItems.map(([id,label],i)=>`<button data-route="${id}" class="nav-link"><span class="nav-icon">${['⌂','⌁','▣','▤','◫','◌','▦'][i]}</span><span>${label}</span>${id==='scan'?'<em>LIVE</em>':''}</button>`).join('');
 mobile.innerHTML=navItems.map(([id,label])=>`<button data-route="${id}" class="nav-link">${label}</button>`).join('');
 $('#mobile-menu').onclick=()=>mobile.classList.toggle('hidden');
}
export function showApp(){ $('#login').classList.add('hidden'); $('#app').classList.remove('hidden'); }
export function renderLogin(onLogin){ $('#login').innerHTML=`<div class="login-page"><div class="login-orb orb-one"></div><div class="login-orb orb-two"></div><div class="login-grid"><div class="login-story"><div class="brand large"><div class="brand-mark">✓</div><div><div class="brand-name">PackSure <span>AI</span></div><div class="brand-sub">LEGAL METROLOGY INTELLIGENCE</div></div></div><div class="eyebrow">FIELD INSPECTION PLATFORM</div><h1>Scan the package.<br><span>Know the risk.</span></h1><p>AI-assisted label extraction, compliance validation and explainable inspection intelligence built for real-world field work.</p><div class="story-stats"><div><b>OCR</b><small>Label extraction</small></div><div><b>RULES</b><small>Requirement checks</small></div><div><b>TRACE</b><small>Inspection history</small></div></div></div><div class="login-card"><div class="eyebrow">INSPECTOR ACCESS</div><h2>Welcome back</h2><p>Launch the prototype console with a demo identity.</p><label>Inspector ID<input value="LM-2048"></label><label>Password<input type="password" value="demo123"></label><button id="sign-in" class="btn-primary full">Sign in to console <span>→</span></button><button id="try-demo" class="btn-secondary full">Enter demo mode</button><div class="secure-line">✓ Browser-first demo · no API key required</div><div class="login-disclaimer">PackSure AI is a technology prototype for automated compliance assistance. Final determinations should be verified by authorized officials.</div></div></div></div>`; $('#sign-in').onclick=onLogin; $('#try-demo').onclick=onLogin; }
